- name: Run async command
  hosts: all
  #strategy: debug
  tasks:
  - include: tasks/commandasync.yml
  - async_status: jid={{ command_result.ansible_job_id }}
    register: job_result
    until: job_result.finished
    retries: 10
  - name: Panic task
    command: /bin/inexistant_folder/null_command
    register: result
    ignore_errors: True
    failed_when:
      - '"ERROR" in result.stderr'
      - result.rc == 2
